"""add currency to bank_balances

Revision ID: c418f49cdb52
Revises: f58ca177ac66
Create Date: 2026-02-10 14:53:38.904494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c418f49cdb52'
down_revision: Union[str, None] = 'f58ca177ac66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_balances', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_balances', 'currency')
    # ### end Alembic commands ###
